steps:
###########################################################
# Step 0: Create a Docker image with Python and Pytest installed
###########################################################
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '--tag=gcr.io/$PROJECT_ID/dataflow-streaming-sentiment-pipeline'
    - '.'

###########################################################
# Step 1: Run unit tests
###########################################################
- name: 'gcr.io/$PROJECT_ID/dataflow-streaming-sentiment-pipeline'
  entrypoint: 'python3'
  args: ["-m",  "pytest", "--disable-pytest-warnings"]